version: '3.9.6'
services:
  web:
    build: ./services/web
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: python manage.py run -h 0.0.0.0
    ports:
      - '8080:8080'
      - 5000:5000
    env_file:
      - ./.env.dev